### ISSUE TITLE
还要服务端配合啊。。

### ISSUE THREAD

**Issue by AweiLoveAndroid** [codezjx/AndLinker#1]
看来这个嗨有待和服务端配合。。
有没有服务端的相关demo

**Comment by lpc904586134** [comment]
ipc和服务端有什么关系

**Comment by codezjx** [comment]
@AweiLoveAndroid `sample`里面的`RemoteService`就可以看做是Server端，通过`android:process`指定了单独进程~  `BindingActivity`可以看做是Client端

**Comment by zhaoxiuyu** [comment]
客户端和服务端 相关的类 包名要一样的吗？

**Comment by codezjx** [comment]
@zhaoxiuyu 传输的Parcelable对象需要在同一包下，跟AIDL一样，否则无法反序列化~  远程接口没要求，随便放，两端保证一样的`@ClassName`和`@MethodName`即可~

**Comment by codezjx** [comment]
发了新的`0.7.1`版本，简化了API，去除了`@ClassName`和`@MethodName`，用`@RemoteInterface`代替即可~
