### ISSUE TITLE
请教下服务端如何主动发数据给客户端

### ISSUE THREAD

**Issue by Ginno-suhg** [codezjx/AndLinker#15]

**Comment by codezjx** [comment]
可以参考下sample项目中的[IRemoteCallback](https://github.com/codezjx/AndLinker/blob/master/sample/src/main/java/com/example/andlinker/IRemoteCallback.java)实现
注册一个远程接口给到服务端，然后服务端主动调用，发送数据 @Ginno-suhg

**Comment by cjunopen** [comment]
> 可以参考下sample项目中的[IRemoteCallback](https://github.com/codezjx/AndLinker/blob/master/sample/src/main/java/com/example/andlinker/IRemoteCallback.java)实现 注册一个远程接口给到服务端，然后服务端主动调用，发送数据 @Ginno-suhg

客户端跟服务端是不同APP的时候可以用的吗，断点看貌似是null的，且注册完回调应该也需要反注册吧

**Comment by codezjx** [comment]
@scp1011 可以的，确保两个App依赖一样的远程接口即可，例如把接口放在Lib库里面，两个App依赖这个Lib即可，sample项目里面通过`android:process=":remote"`来模拟不同进程间的通讯，可以理解为已经是2个App了。注册与反注册的方式在sample里面都有了，建议可以再详细看下哈。
