### ISSUE TITLE
如果是2个 APP  有示例吗？

### ISSUE THREAD

**Issue by jing1007209484** [codezjx/AndLinker#17]
如果是2个 APP  有示例吗？

**Comment by codezjx** [comment]
@jing1007209484 你是想问Server和Client分别在两个App中的示例吗？Sample为了演示方便，是通过`android:process`来模拟不同进程 ，其实两个App的示例代码其实是一样的，确保两个App引用同一个`@RemoteInterface`接口就行。

**Comment by jing1007209484** [comment]
***@***.***接口就行&nbsp; 是怎么定义的&nbsp; &nbsp;我一个是package com.Toolbox.AccessTools.IRemoteService;

import com.codezjx.andlinker.annotation.RemoteInterface;

/**
 * @author Administrator
 */
@RemoteInterface
public interface IRemoteService {
    int getPid();
}
----------------------------------------------------------------------------------
package com.scrcpy.Server.IRemoteService;


import com.codezjx.andlinker.annotation.RemoteInterface;

/**
 * @author Administrator
 */
@RemoteInterface()
public interface RemoteService {
    int getPid();
}                      怎么也连接不上去


&nbsp;


梦幻雪月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月22日(星期一) 下午2:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codezjx/AndLinker] 如果是2个 APP  有示例吗？ (Issue #17)












@jing1007209484 你是想问Server和Client分别在两个App中的示例吗？Sample为了演示方便，是通过android:process来模拟不同进程 ***@***.***接口就行。

**Comment by codezjx** [comment]
@jing1007209484 我看这个接口定义没什么问题，需要确认下Server端是否已经通过registerObject把接口实现注册到AndLinkerBinder，如果可以，提供下完整的demo项目来分析下。

**Comment by jing1007209484** [comment]
服务端 
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools"
package="com.Toolbox.AccessTools">


<service
android:name=".IRemoteService.MyRemoteService"
android:enabled="true"
android:exported="true">
<intent-filter>
<action android:name="com.Toolbox.AccessTools.REMOTE_SERVICE_ACTION" />
</intent-filter>
</service>


package com.Toolbox.AccessTools.IRemoteService;
import com.codezjx.andlinker.annotation.RemoteInterface;

/**
* @author Administrator
*/
@RemoteInterface
public interface IRemoteService {
int getPid();
}


package com.Toolbox.AccessTools.IRemoteService;

import android.app.Service;
import android.content.Intent;
import android.os.IBinder;


import com.Toolbox.AccessTools.MyLog;
import com.codezjx.andlinker.AndLinkerBinder;

public class MyRemoteService extends Service {
private static final String TAG = MyRemoteService.class.getName();

public MyRemoteService() {
}
private AndLinkerBinder mLinkerBinder;

@Override
public IBinder onBind(Intent intent) {
MyLog.d(TAG, "Service onBind()");
return mLinkerBinder;
}

@Override
public void onCreate() {
super.onCreate();
MyLog.d(TAG, "跨进程服务端开启");
mLinkerBinder = AndLinkerBinder.Factory.newBinder();
mLinkerBinder.registerObject(mRemoteService);
}
@Override
public void onDestroy() {
super.onDestroy();
MyLog.d(TAG, "服务销毁");
mLinkerBinder.unRegisterObject(mRemoteService);
mLinkerBinder=null;

}
private final IRemoteService mRemoteService = new IRemoteService() {

@Override
public int getPid() {
return android.os.Process.myPid();
}

};
}

客户端
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools">

<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"
tools:ignore="QueryAllPackagesPermission" />
<queries>
<package android:name="com.Toolbox.AccessTools"/>
</queries>


<application
android:allowBackup="true"
android:dataExtractionRules="@xml/data_extraction_rules"
android:fullBackupContent="@xml/backup_rules"
android:icon="@mipmap/ic_launcher"
android:label="@string/app_name"
android:roundIcon="@mipmap/ic_launcher_round"
android:supportsRtl="true"
android:theme="@style/Theme.MyServer"
tools:targetApi="31">

<activity
android:name=".MainActivity"
android:enabled="true"
android:exported="true">

<intent-filter>
<action android:name="android.intent.action.MAIN" />
<category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
</activity>
</application>

</manifest>


package com.scrcpy.Server.IRemoteService;


import com.codezjx.andlinker.annotation.RemoteInterface;

/**
* @author Administrator
*/
@RemoteInterface()
public interface RemoteService {
int getPid();
}


package com.scrcpy.Server;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import com.codezjx.andlinker.AndLinker;

import com.scrcpy.Server.IRemoteService.RemoteService;

public class MainActivity extends AppCompatActivity implements AndLinker.BindCallback {

private AndLinker mLinker;
private RemoteService mRemoteService;
private String TAG="客户端";
private static final String REMOTE_SERVICE_PKG = "com.Toolbox.AccessTools";
public static final String REMOTE_SERVICE_ACTION = "com.Toolbox.AccessTools.REMOTE_SERVICE_ACTION";
@Override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
setContentView(R.layout.activity_main);
MyLog.d(TAG, "onCreate: ");
//AndLinker.enableLogger(false);


AndLinker.enableLogger(true);
mLinker = new AndLinker.Builder(this)
.packageName(REMOTE_SERVICE_PKG)
.action(REMOTE_SERVICE_ACTION)
// Specify the callback executor by yourself
//.addCallAdapterFactory(OriginalCallAdapterFactory.create(callbackExecutor))
//.addCallAdapterFactory(OriginalCallAdapterFactory.create()) // Basic
//.addCallAdapterFactory(RxJava2CallAdapterFactory.create())// RxJava2
.build();
mLinker.setBindCallback(this);
mLinker.bind();

try {
mRemoteService = mLinker.create(RemoteService.class);
if (mRemoteService==null)
{
MyLog.d(TAG, "mRemoteService ",mRemoteService);
}else
{
MyLog.d(TAG, "获取 PID ",mRemoteService.getPid());
}
} catch (Exception e) {
MyLog.d(TAG, "onCreate: ",e.getMessage());
}

}
@Override
public void onBind() {
MyLog.d(TAG, "AndLinker onBind()");
mRemoteService = mLinker.create(RemoteService.class);
MyLog.d(TAG, "onBind: ",mRemoteService.getPid());
}
@Override
public void onUnBind() {
MyLog.d(TAG, "AndLinker onUnBind()");
mRemoteService = null;
}
@Override
protected void onDestroy() {
super.onDestroy();
mLinker.unbind();
mLinker.setBindCallback(null);
}
}

**Comment by jing1007209484** [comment]
demo  找到哪里的问题了嘛  我这还是一直连接不上

**Comment by codezjx** [comment]
@jing1007209484 这应该是bindService的权限问题，不是库的问题，你可以自己简单写个bindService()看能不能正常绑定上。另外看下代码是不是targets Android 11及以上？如果是，需要在client的manifest下增加以下字段：
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
...
    <queries>
        <intent>
            <action android:name="com.Toolbox.AccessTools.REMOTE_SERVICE_ACTION" />
        </intent>
    </queries>
...
</manifest>
```

参考：
https://developer.android.com/training/package-visibility/declaring
