### ISSUE TITLE
callback 无法使用

### ISSUE THREAD

**Issue by gzplace** [codezjx/AndLinker#2]
我按照 sample 中的方式 在service端 编写了相应的接口 
类似:
@RemoteInterface
public interface ITestCallback {
    void onTestFired();
}

并且在 App端 调用 linker.registerObject(mTestCallback)
  mTestCallBack 为本地实现接口
但在 service 中无法获取此接口，故无法反调此callback，或许使用有误，还请告知正确步骤，谢谢！

**Comment by codezjx** [comment]
@gzplace 在`Service`端暴露的远程接口`IRemoteService `中，需要提供注册`Callback`的方法呀~  这样`Client`端就可以通过`registerCallback`方法把`Callback`跨进程传到`Service`端了呀，然后就能回调啦~  在`README`和`Sample`里面都相关的代码和描述，建议再仔细阅读一次哦~
```java
@RemoteInterface
public interface IRemoteService {
    ...
    void registerCallback(@Callback ITestCallback callback);
    ...
}
```
