### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by woniu0936** [codezjx/AndLinker#3]
我想实现一个主进程，多个副进程的通信，希望是所有副进程给主进程传数据，应该怎么写？
我看你BindingActivity代码里面有这么一段：
```
mLinker = new AndLinker.Builder(this)
                .packageName(REMOTE_SERVICE_PKG)
                .action(REMOTE_SERVICE_ACTION)
                // Specify the callback executor by yourself
                //.addCallAdapterFactory(OriginalCallAdapterFactory.create(callbackExecutor))
                .addCallAdapterFactory(OriginalCallAdapterFactory.create()) // Basic
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())  // RxJava2
                .build();
```
那如果是多个remote进程的话，是要注册多个action？怎么注册？麻烦赐教，谢谢

**Comment by codezjx** [comment]
@woniu0936 提供IPC服务的进程是主进程吧？那多个副进程统一通过上面的代码就能连上并获取到远程服务接口啦，packageName和action都是同一个啊，底层实现就是bindService哦~

**Comment by woniu0936** [comment]
各进程之间只有副进程的activity给主进程的activity传递数据，没有service，这个框架适合吗？

**Comment by codezjx** [comment]
@woniu0936 目前不支持`Activity`与`Activity`直接通信~  服务端需要实现`Service`的哈~  此框架仅作为`AIDL`的替代品~

**Comment by woniu0936** [comment]
哦哦，那如果换成在主进程开一个service，多个副进程的activity给主进程的service发送数据呢？

**Comment by codezjx** [comment]
@woniu0936 这样是支持的哈~   子进程的`Activity`统一bind到主进程即可，详见sample，里面代码都很详细了。

**Comment by woniu0936** [comment]
好的，谢谢了
