### ISSUE TITLE
Callback not working right 

### ISSUE THREAD

**Issue by codekeyz** [codezjx/AndLinker#6]
I have implemented a `Callback` according to the docs, and it works fine, just that some codes don't get executed in the Callback function

Here's the code
```kotlin
 private val smsCallback = SMSListener { it ->
        Log.d("FayaPay", it)   // This executes

        Toast.makeText(applicationContext, "A new message just arrived\n $it", Toast.LENGTH_LONG).show()   // This doesn't execute 
    }
```

Please help me out.

**Comment by codekeyz** [comment]
I managed to get this to work using this code 
```kotlin
  runOnUiThread {
        Toast.makeText(applicationContext, "A new message just arrived\n $it", Toast.LENGTH_LONG).show()   // This now executes
  }
```

Any more suggestions to getting this work ?

**Comment by codezjx** [comment]
Because this `Callback` may not run on the main thread, related to the thread that remote server calls this `Callback`. To make this toast show, you need to put these code in main thread.
```java
Handler handler = new Handler(Looper.getMainLooper());
handler.post(() -> Toast.makeText(context, "Message", Toast.LENGTH_LONG).show());
```

**Comment by codekeyz** [comment]
Thanks so much @codezjx
