### ISSUE TITLE
How to implement the library for two seprate application

### ISSUE THREAD

**Issue by paragsarkar** [codezjx/AndLinker#8]
Hi Wanted to know if we can implement the project in two seprate application the aidl works around

**Comment by codekeyz** [comment]
Yes it will definitely work. The Docs contain pretty awesome guidelines to get you started.

**Comment by codezjx** [comment]
@paragsarkar Yes, as @codekeyz says. You can copy the original `@RemoteInterface` to another project or application, keep the original interface name and method name. That's it!
