### ISSUE TITLE
如何支持多个客户端？

### ISSUE THREAD

**Issue by CooperCao** [codezjx/AndLinker#9]
比如有两个APP要连接到同一个服务？另外请教一下，如果有多个客户端连接的时候，服务端该如何保证线程安全？谢谢。

**Comment by codezjx** [comment]
@CooperCao 
1. 多个`App`可以使用同一个`Lib`，然后把`@RemoteInterface`修饰的远程服务接口放在`Lib`中，供多个`App`使用。或者可以直接拷贝远程服务接口到另一个`App`中，保持接口的类名和方法名一致即可，详见`README`文档。
2. 无论多少个客户端连接，服务端的远程服务接口方法都是运行在Binder线程池中的（这点跟AIDL的Binder通信一致），需要自行处理线程同步~
